[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "libGL", "mesa", "mesa_drivers"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "python3 main.py"