[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "gcc",
  "libGL",
  "mesa",
  "mesa_drivers",
  "libGLU",
  "libGLU_dev",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libSM",
  "xorg.libICE"
]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "ls /nix/store | grep libGL",
  "find / -name libGL.so.1 || true"
]

[phases.start]
cmd = "python3 main.py"